export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  RESTAURANT_OWNER = 'RESTAURANT_OWNER',
  REGIONAL_MANAGER = 'REGIONAL_MANAGER',
  STORE_MANAGER = 'STORE_MANAGER',
  CASHIER = 'CASHIER',
  KITCHEN_STAFF = 'KITCHEN_STAFF',
  WAITER = 'WAITER',
  DELIVERY_STAFF = 'DELIVERY_STAFF',
  INVENTORY_MANAGER = 'INVENTORY_MANAGER',
  HR = 'HR',
  ACCOUNTANT = 'ACCOUNTANT',
  CUSTOMER = 'CUSTOMER'
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  PLACED = 'PLACED',
  IN_PREPARATION = 'IN_PREPARATION',
  READY = 'READY',
  SERVED = 'SERVED',
  PAID = 'PAID',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED'
}

export enum OrderItemStatus {
  QUEUED = 'QUEUED',
  COOKING = 'COOKING',
  BUMPED = 'BUMPED',
  SERVED = 'SERVED',
  VOIDED = 'VOIDED'
}

export enum OrderType {
  DINE_IN = 'DINE_IN',
  TAKEOUT = 'TAKEOUT',
  DELIVERY = 'DELIVERY'
}

export enum TableStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  OCCUPIED = 'OCCUPIED',
  BILL_REQUESTED = 'BILL_REQUESTED',
  BUSSING = 'BUSSING',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE'
}

export enum PaymentMethod {
  CASH = 'CASH',
  CREDIT_CARD = 'CREDIT_CARD',
  APPLE_PAY = 'APPLE_PAY',
  GOOGLE_PAY = 'GOOGLE_PAY',
  GIFT_CARD = 'GIFT_CARD'
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED'
}

export enum IngredientUnit {
  KG = 'KG',
  GRAM = 'GRAM',
  LITER = 'LITER',
  ML = 'ML',
  PIECE = 'PIECE',
  PACKET = 'PACKET',
  BOX = 'BOX',
  BOTTLE = 'BOTTLE',
  CAN = 'CAN'
}

export enum PurchaseOrderStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  RECEIVED = 'RECEIVED',
  CANCELLED = 'CANCELLED'
}

export enum ShiftType {
  MORNING = 'MORNING',
  AFTERNOON = 'AFTERNOON',
  EVENING = 'EVENING',
  NIGHT = 'NIGHT',
  FULL_DAY = 'FULL_DAY'
}

export enum AuditAction {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REFUND_OVERRIDE = 'REFUND_OVERRIDE',
  VOID_OVERRIDE = 'VOID_OVERRIDE',
  INVENTORY_ADJUSTMENT = 'INVENTORY_ADJUSTMENT'
}

export enum KitchenStation {
  GRILL = 'GRILL',
  COLD_PREP = 'COLD_PREP',
  BAR = 'BAR',
  ASSEMBLY = 'ASSEMBLY',
  PASS_EXPEDITER = 'PASS_EXPEDITER'
}

export enum ReservationStatus {
  CONFIRMED = 'CONFIRMED',
  CHECKED_IN = 'CHECKED_IN',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  COMPLETED = 'COMPLETED'
}
